import { createClient } from "@supabase/supabase-js";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

import ReportPollingState from "@/src/components/ReportPollingState";

export default async function ReportPage({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params;

  // 1. Initialize Supabase (Service Role to bypass RLS for now)
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  // 2. Fetch from 'reports' table
  const { data: report, error } = await supabase
    .from("reports")
    .select("content_md, generated_at")
    .eq("project_id", projectId)
    .single();

  // 3. Handle 'not found' or 'error' state
  if (error || !report) {
    return <ReportPollingState />;
  }

  // 4. Return the beautifully rendered Markdown UI
  return (
    <main style={{ maxWidth: "800px", margin: "0 auto", padding: "60px 24px" }}>
      {/* Top Navigation */}
      <div style={{ marginBottom: "40px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <Link 
          href="/" 
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: "8px",
            color: "var(--muted)",
            textDecoration: "none",
            fontSize: "14px",
            fontWeight: 500,
            transition: "color 0.2s"
          }}
        >
          <ArrowLeft size={16} /> Back to Upload
        </Link>

        <Link
          href={`/chat/${projectId}`}
          className="glow-button"
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: "8px",
            padding: "8px 16px",
            background: "var(--card-bg)",
            border: "1px solid var(--accent)",
            color: "var(--accent)",
            borderRadius: "8px",
            textDecoration: "none",
            fontWeight: 600,
            fontSize: "14px",
          }}
        >
          💬 Ask Questions
        </Link>
      </div>

      {/* Header Context */}
      <div style={{ marginBottom: "40px", paddingBottom: "24px", borderBottom: "1px solid var(--card-border)" }}>
        <p style={{ color: "var(--accent)", fontWeight: 600, fontSize: "14px", marginBottom: "8px", textTransform: "uppercase", letterSpacing: "0.05em" }}>
          Generated Spec Report
        </p>
        <p style={{ color: "var(--muted)", fontSize: "14px" }}>
          Project ID: <code style={{ background: "var(--card-bg)", padding: "2px 6px", borderRadius: "4px" }}>{projectId}</code>
        </p>
        <p style={{ color: "var(--muted)", fontSize: "14px", marginTop: "4px" }}>
          Generated: {new Date(report.generated_at).toLocaleString()}
        </p>
      </div>

      {/* Rendered Markdown */}
      <article className="markdown-body">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {report.content_md}
        </ReactMarkdown>
      </article>

      {/* Footer */}
      <footer style={{ marginTop: "80px", paddingTop: "40px", borderTop: "1px solid var(--card-border)", textAlign: "center", color: "var(--muted)", fontSize: "14px" }}>
        <p>Generated by <strong>Corro</strong> — The open-source evidence layer for spec-driven development.</p>
      </footer>
    </main>
  );
}
